version: "3"

networks:
  fibonacci:
    internal: true
services:
 grafana:
    build: ./
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
    ports:
      - "3000:3000"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - fibonacci
      - default
    restart: always

 prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - fibonacci
      - default
    restart: always

 black-exporter:
    image: prom/blackbox-exporter:latest
    container_name: black-exporter
    ports:
      - 9115:9115
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - fibonacci
      - default
    restart: always